# Header

menu:
  主页: /
  归档: /archives/

sub:
  电影: movie.

# SubNav
subnav:
  mail: "mailto:lizhen55521@gmail.com"
  github: "https://github.com/Leo555"
  weibo: "https://weibo.com/515679943"
  rss: /atom.xml
  #zhihu: "#"
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root:

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: true

# Miscellaneous
baidu_analytics: '0391cafd2247c0b68b9de35abf29c6d1'

favicon: /assets/img/favicon.ico

#你的头像url
avatar: /assets/img/avatar.svg

#2、网易云跟帖
wangyiyun: false

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: 'Links'
  aboutme: '关于我'

friends:
  Leo的学习日志: http://poacherbro.github.io/
  wxsm's space: https://wxsm.space/
  James Whitesaber: http://whitesaber.farbox.com/
  Jason's Blog: https://blog.aquariuslt.com/
  jgchen: http://blog.jgchen.xin/home/
  Movie: https://movie.lz5z.com/
  动画: https://lz5z.com/animatable/

aboutme: <div>精通 JavaScript、Python、Ruby、Java、Lisp等技术<sup>名词拼写</sup>。
        擅长各种从入门到放弃。
        毕业于世界著名学府——北大<sup>青鸟</sup>。
        如果你也有志于成为一名程序员<sup>鼓励师</sup>的话，请联系我。</div>
