# Header

menu:
  主页: /
  归档: /archives

# SubNav
subnav:
  mail: "mailto:lizhen55521@gmail.com"
  github: "https://github.com/Leo555"
  weibo: "http://weibo.com/515679943"
  rss: /atom.xml
  #zhihu: "#"
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: true

# 打赏
# 请在需要打赏的文章的md文件头部，设置属性reward: true

# 打赏基础设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: 王炸！好我赢了
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: /assets/img/alipay.jpg
# 微信二维码图片地址
weixin: /assets/img/wechat.jpg

# Miscellaneous
baidu_analytics: '0391cafd2247c0b68b9de35abf29c6d1'

favicon: /assets/img/favicon.ico

#你的头像url
avatar: /assets/img/avatar.png

#是否开启分享
share_jia: true

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: ""

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: 'Links'
  aboutme: '关于我'

friends:
  Leo的学习日志: http://poacherbro.github.io/
  wxsm's space: https://wxsm.space/
  James Whitesaber: http://whitesaber.farbox.com/
  
aboutme: <div>精通 JavaScript、Python、Ruby、Java、Lisp等技术<sup>名词拼写</sup>。
        擅长各种从入门到放弃。
        毕业于世界著名学府——北大<sup>青鸟</sup>。
        如果你也有志于成为一名程序员<sup>鼓励师</sup>的话，请联系我。</div>
