language: node_js
cache:
  directories:
  - node_modules
node_js: stable

install:
  - npm install

script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "Leo555"
  - git config user.email "lizhen55521@gmail.com"
  - git add .
  - git commit -m "Update"
  - git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - master

env:
 global:
   - GH_REF: github.com/Leo555/Leo555.github.io.git