language: node_js
node_js: stable

install:
  - npm install

script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - ls
  - git init
  - git config user.name "LeoLi"
  - git config user.email "lizhen55521@gmail.com"
  - git add .
  - git commit -m "Update"
  - git push --force --quiet "https://${GitHub_token}@${GH_REF}" master:master

branches:
  only:
    - master

env:
 global:
   - GH_REF: github.com/Leo555/Leo555.github.io.git